{
    "Modified": "2020-02-18T19:28:00",
    "Published": "2010-05-27T19:30:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "assigner": "cve@mitre.org",
    "capec": [],
    "cvss": 5.0,
    "cvss-time": "2020-02-18T19:28:00",
    "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
    "cwe": "CWE-787",
    "id": "CVE-2009-4134",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "NONE",
        "integrity": "NONE"
    },
    "last-modified": "2020-02-18T19:28:00",
    "redhat": {
        "advisories": [
            {
                "rhsa": {
                    "id": "RHSA-2011:0027"
                }
            },
            {
                "rhsa": {
                    "id": "RHSA-2011:0260"
                }
            }
        ],
        "rpms": [
            "python-0:2.4.3-43.el5",
            "python-debuginfo-0:2.4.3-43.el5",
            "python-devel-0:2.4.3-43.el5",
            "python-libs-0:2.4.3-43.el5",
            "python-tools-0:2.4.3-43.el5",
            "tkinter-0:2.4.3-43.el5",
            "python-0:2.3.4-14.9.el4",
            "python-debuginfo-0:2.3.4-14.9.el4",
            "python-devel-0:2.3.4-14.9.el4",
            "python-docs-0:2.3.4-14.9.el4",
            "python-tools-0:2.3.4-14.9.el4",
            "tkinter-0:2.3.4-14.9.el4"
        ]
    },
    "references": [
        "http://bugs.python.org/issue8678",
        "http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html",
        "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html",
        "http://secunia.com/advisories/42888",
        "http://secunia.com/advisories/43068",
        "http://secunia.com/advisories/43364",
        "http://support.apple.com/kb/HT4435",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215",
        "http://www.redhat.com/support/errata/RHSA-2011-0027.html",
        "http://www.redhat.com/support/errata/RHSA-2011-0260.html",
        "http://www.securityfocus.com/bid/40361",
        "http://www.vupen.com/english/advisories/2011/0122",
        "http://www.vupen.com/english/advisories/2011/0212",
        "http://www.vupen.com/english/advisories/2011/0413",
        "https://bugzilla.redhat.com/show_bug.cgi?id=541698"
    ],
    "refmap": {
        "apple": [
            "APPLE-SA-2010-11-10-1"
        ],
        "bid": [
            "40361"
        ],
        "confirm": [
            "http://bugs.python.org/issue8678",
            "http://support.apple.com/kb/HT4435",
            "https://bugzilla.redhat.com/show_bug.cgi?id=541698"
        ],
        "mandriva": [
            "MDVSA-2010:215"
        ],
        "secunia": [
            "42888",
            "43068",
            "43364"
        ],
        "suse": [
            "SUSE-SR:2011:002"
        ],
        "vupen": [
            "ADV-2011-0122",
            "ADV-2011-0212",
            "ADV-2011-0413"
        ]
    },
    "summary": "Buffer underflow in the rgbimg module in Python 2.5 allows remote attackers to cause a denial of service (application crash) via a large ZSIZE value in a black-and-white (aka B/W) RGB image that triggers an invalid pointer dereference.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:2.5.0:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:2.5.0:*:*:*:*:*:*:*"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": [
        "cpe:2.3:a:python:python:2.5.0:*:*:*:*:*:*:*"
    ]
}