{
    "Modified": "2020-07-04T23:15:00",
    "Published": "2020-07-04T23:15:00",
    "access": {},
    "assigner": "cve@mitre.org",
    "cvss": 5.0,
    "cwe": "Unknown",
    "id": "CVE-2020-15523",
    "impact": {},
    "last-modified": "2020-07-06T12:19:00",
    "references": [
        "https://bugs.python.org/issue29778",
        "https://github.com/python/cpython/pull/21297"
    ],
    "summary": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
    "vulnerable_configuration": [],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": []
}