{
    "Modified": "2013-05-14T23:08:53.080-04:00",
    "Published": "2010-05-27T15:30:01.767-04:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "capec": [],
    "cvss": 5.0,
    "cvss-time": "2010-05-28T10:47:00.000-04:00",
    "cwe": "CWE-189",
    "id": "CVE-2010-1634",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "NONE",
        "integrity": "NONE"
    },
    "map_cve_bid": {
        "bidid": "40370"
    },
    "map_cve_fedora": {
        "fedoraid": "FEDORA-2010-9652"
    },
    "map_cve_iavm": {
        "disakey": "V0031252",
        "iavmid": "2012-A-0020",
        "iavmtitle": "Multiple Vulnerabilities in VMware ESX 4.1 and ESXi 4.1"
    },
    "map_cve_nessus": {
        "nessus_script_family": "Ubuntu Local Security Checks",
        "nessus_script_file": "ubuntu_USN-1616-1.nasl",
        "nessus_script_id": "62700",
        "nessus_script_name": "Ubuntu 10.04 LTS / 11.04 : python3.1 vulnerabilities (USN-1616-1)"
    },
    "map_cve_openvas": {
        "openvas_script_family": "Fedora Local Security Checks",
        "openvas_script_file": "gb_fedora_2010_9565_python_fc12.nasl",
        "openvas_script_id": "862218",
        "openvas_script_name": "Fedora Update for python FEDORA-2010-9565"
    },
    "map_cve_oval": {
        "cpeid": "",
        "ovalclass": "patch",
        "ovalid": "oval:org.mitre.oval:def:18043",
        "ovaltitle": "USN-1596-1 -- python2.6 vulnerabilities"
    },
    "map_cve_redhat": {
        "redhatid": "RHSA-2011:0491",
        "redhatovalid": "oval:com.redhat.rhsa:def:20110491",
        "redhatupdatedesc": "RHSA-2011:0491: python security update (Moderate)"
    },
    "map_cve_scip": {
        "scipid": "53381",
        "sciplink": "http://www.scip.ch/en/?vuldb.53381"
    },
    "map_cve_suse": {
        "suseid": "SUSE-SR:2011:002"
    },
    "map_cve_ubuntu": {
        "ubuntuid": "USN-1616-1"
    },
    "map_redhat_bugzilla": {
        "advisory_dateissue": "2011-05-05",
        "bugzillaid": "690560",
        "bugzillatitle": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)",
        "redhatid": "RHSA-2011:0491"
    },
    "ranking": [
        [
            {
                "circl": 2
            }
        ]
    ],
    "references": [
        "https://bugzilla.redhat.com/show_bug.cgi?id=590690",
        "http://svn.python.org/view?rev=81079&view=rev",
        "http://svn.python.org/view?rev=81045&view=rev",
        "http://bugs.python.org/issue8674",
        "http://www.vupen.com/english/advisories/2011/0212",
        "http://www.vupen.com/english/advisories/2011/0122",
        "http://www.vupen.com/english/advisories/2010/1448",
        "http://www.ubuntu.com/usn/USN-1616-1",
        "http://www.ubuntu.com/usn/USN-1613-2",
        "http://www.ubuntu.com/usn/USN-1613-1",
        "http://www.ubuntu.com/usn/USN-1596-1",
        "http://www.securityfocus.com/bid/40370",
        "http://www.redhat.com/support/errata/RHSA-2011-0027.html",
        "http://support.apple.com/kb/HT5002",
        "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html",
        "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html",
        "http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html",
        "http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html"
    ],
    "summary": "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:2.6",
            "title": "Python 2.6"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7",
            "title": "Python 2.7"
        },
        {
            "id": "cpe:2.3:a:python:python:3.1",
            "title": "Python 3.1"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2",
            "title": "Python 3.2"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python:python:2.6",
        "cpe:/a:python:python:2.7",
        "cpe:/a:python:python:3.1",
        "cpe:/a:python:python:3.2"
    ]
}